import {
    OPENAI_API_KEY,
    PORT,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI,
    ALLOWED_ORIGINS,
    AWS_REGION,
    S3_VECTOR_BUCKET,
    S3_VECTOR_INDEX,
    EMBEDDING_MODEL,
    AWS_S3_BUCKET_NAME
} from '../config/index.js';

export {
    OPENAI_API_KEY,
    PORT,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI,
    ALLOWED_ORIGINS,
    AWS_REGION,
    S3_VECTOR_BUCKET,
    S3_VECTOR_INDEX,
    EMBEDDING_MODEL,
    AWS_S3_BUCKET_NAME
};

